AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'spec/spec_helper.rb'

# Railsプロジェクトの特性に合わせた設定
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'
    - 'config/routes.rb'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/migrate/*'
  AllowedMethods:
    - 'questionnaire_params'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'
    - 'db/migrate/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
